### ISSUE TITLE
Comparison of yields of 32 and 29

### ISSUE THREAD

**Issue by mattodd** [opensourcecatalysis/OPS-Paper1#13]
In one case (for compound 29) ketone used, in other case (giving 32) ketal. Is this a valid comparison? Do we need another experiment here?

**Comment by mattodd** [comment]
Remains a problem. @katb did you do these two? A comparison is hard here. We are on the one hand saying that hydroxytyrosol is worse (compound 31 formed in lower yield than 24) and also better (compound 32 formed in higher yield than 29) but the problem is that we used a ketal for the synthesis of compound 32. I assume we don't have the corresponding experiments using a ketal for the synthesis of 29 or a ketone for the synthesis of 32? In which case do we just need to ignore this whole thing here for the moment?

**Comment by paulking1995** [comment]
This is OK because it's comparing:
24 vs 31 (common aldehyde used, different alcohol (ie dihydroxy vs dimethoxy)
29 vs 32 (common ketone, different alcohol (ie dihydroxy vs dimethoxy again)

So, there's 4 different experiments going on here. It's showing that when using methoxy, it's not compatible with ketones (29) but the reaction seems to be slightly lower yielding with aldehydes.
